name: butterflyai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - requests
  - python-dotenv
  - tabulate # for the notebook
  - pip:
      - tensorflow
      - tensorflow-metal
      - tf-keras
